config/routes.rb
Todone::Application.routes.draw do
    
  devise_for :users
  
  root :to => "lists#index"
  resources :lists do
    resources :tasks do
      member do
        put "toggle_completed"
      end
    end
  end
  
  #match :toggle_completed => "tasks#completed"

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :tasks, :dependent => :destroy
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true

  def delete(current_list)
    current_list.deleted = true
  end

  def complete(current_list)
    current_list.completed = true
  end
  
  def completed?(current_list)
    i = 0
    current_lists.tasks.each do |task|
      i += 1 if task.completed?
      complete(current_list) if i == current_lists.tasks.length
    end
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :due_date, :completed, :priority
  
  belongs_to :list
  
  validates :name, :priority, presence: :true
  
  # before_validation :default_priority#, :set_incomplete
  
  def default_priority
    self.priority = 1 unless self.priority
  end
  
  # def set_incomplete
  #   self.completed = false
  # end
  
end


# create_table "tasks", :force => true do |t|
#   t.integer  "list_id"
#   t.string   "name"
#   t.date     "due_date"
#   t.boolean  "completed"
#   t.integer  "priority"
#   t.datetime "created_at", :null => false
#   t.datetime "updated_at", :null => false
# end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :lists, :dependent => :destroy
  has_many :tasks, :through => :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
  end
  
  def show
    @list = List.find(params[:id])
    @task = Task.new
    @tasks = Task.all
  end
  
  def edit
  end
  
  def index
    @list = List.new
    @list.user = current_user
  end

  
  def create
    @list = List.new(params[:list])
    @list.user = current_user
    if @list.save
      flash[:success] = "New To Do List created!"
      redirect_to root_path
    else
      flash.now[:error] = "Woops! Something went wrong.. :("
      render :action => 'index' 
    end
  end
  
  def destroy
    @list = List.find_by_id(params[:id])
    @list.destroy
    redirect_to root_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @list = List.find(params[:list_id])

    #@task = @list.tasks.build(params[:task])

    @task = Task.new(params[:task])
    @task.list_id = @list.id
    # @task.list = @list

    if @task.save
      flash[:notice] = "New ToDo created!"
      redirect_to list_path(@list)
    else
      flash.now[:error] = "Woops! Something went wrong.. :("
      render 'lists/show'
    end
  end

  def edit
  end
  
  def toggle_completed
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.completed ? @task.completed = false : @task.completed = true
    if @task.save
      flash[:notice] = "Task completed: #{@task.completed}"
      redirect_to list_path(@list)
    else
      flash.now[:error] = "Woops! Something went wrong with the completed saving.. :("
      render 'lists/show'
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    Task.find(params[:id]).destroy
    flash[:success] = "Short URL Successfully Deleted!"
    redirect_to list_path(@list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def task_completed_button_text state
    state ? "Done" : "Not done"
  end
  
  def task_completed_button_style state
    state ? "btn btn-success" : "btn btn-warning"
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo(ne)</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href="/">
		    	To Do(ne)
		    </a>
				<% if user_signed_in? %>
					<ul class="nav pull-left">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Lists<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<% current_user.lists.each do |list| %>
									<li>	
										<%= link_to list.name, list_path(list) %>
									</li>
								<% end %>
							</ul>
						</li>
					</ul>
				<% end %>
		    <ul class="nav pull-right">
					<%= render 'devise/menu/registration_items' %>
					<%= render 'devise/menu/login_items' %>
			</div>
		</div>
	</div>
	<div class="container">
		<% if notice %>
			<p class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert %>
	  	<p class="alert"><%= alert %></p>
		<% end %>
		
		<% if flash[:notice] %>
		      <p class="notice"><%= flash[:notice] %></p>
		    <% end %>
		    <% if flash[:error] %>
		      <p class="error"><%= flash[:error] %></p>
		    <% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/lists/index.html.erb
<div class="block">
<h3>Welcome <%=current_user.email%>. These are your lists</h3>
</div>
<div class="span9">
	<%= form_for(@list) do |l| %>
		<div class="field">
			<%= l.label :name, 'What is the name of your new list?'%>
			<%= l.text_field :name %>
		</div>
		<div class="field">
			<%= l.label :description, 'Want to add a description?'%>
			<%= l.text_field :description %>
		</div>
		<div class="actions">
			<%= l.submit %>
		</div>
	<% end %>
</div>

<div class="span6">
	<ul>
		<% current_user.lists.each do |list| %>
			<li><%= link_to list.name, list_path(list) %>  <%= link_to "EDIT this list", list, method: :edit, :class => "btn btn-mini"%> |  <%= link_to "delete this list", list, method: :delete, :class => "btn-mini btn-danger"%></li>
		<% end %>
	</ul>
</div>

app/views/lists/show.html.erb
<h2>Add a task to <%= @list.name %></h2>

<div class=>
<%= @list.description %>

<%= form_for [@list, @task] do |l| %>
	<div class="field">
		<%= l.label :name, 'Task Name'%>
		<%= l.text_field :name %>
		
	</div>
	<div class="field">
		<%= l.label :due_date, 'Due Date'%>
		<%= l.text_field :due_date %>
	</div>
	<div class="field">
		<%= l.label :priority, 'Priority'%>
		<%= l.text_field :priority %>
	</div>
	<div class="actions">
		<%= l.submit %>
	</div>
<% end %>
<ul>
	<% @list.tasks.each do |task| %>
		<li>
			<%= task.name %> 
			| <%= link_to task_completed_button_text(task.completed), toggle_completed_list_task_path(@list, task), :method => :put, :class => task_completed_button_style(task.completed) %>  
			| <%= link_to "Delete", list_task_path(@list, task), :class => "btn btn-danger", :method => :delete %>
		</li>
	<% end %>
</ul>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>